# **Tarea de Numpy**

Este notebook es el de los ejercicios >:)

In [ ]:
!pip install numpy
import numpy as np

# Probando si si jala el numpy
my_arreglow = np.array([1, 2, 3, 4, 5])

print(my_arreglow)
print(np.mean(my_arreglow))


[1 2 3 4 5]
3.0


## Ejercicios de refuerzo

### **Ejercicio 1 - Crear un array de ceros:**
Crea un array de tamaño (3, 4) lleno de ceros.

In [ ]:
# Solución (:
arr1 = np.zeros((3,4), dtype=int) #para que no salgan con el puntito
arr1

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

### **Ejercicio 2-  Suma de elementos:**
   Dado el array [1, 2, 3, 4, 5], calcula la suma de todos sus elementos usando NumPy.

In [ ]:
# Solucion :)
array = np.array([1, 2, 3, 4, 5])
res = int(np.sum(array))
print(f"La suma de los elementos es {res}")


La suma de los elementos es 15


### **Ejercicio 3 - Encontrar el máximo y mínimo:**
Dado el array [10, 20, 30, 40, 50], encuentra el valor máximo y mínimo.

In [ ]:
array = np.array([10, 20, 30, 40, 50])
print("El maximo es ", np.max(array), ". El mainimo es ", np.min(array))
# Solución:)

El maximo es  50 . El mainimo es  10


### **Ejercicio 4 - Encontrar el máximo y mínimo:**
 Dado el array [10, 20, 30, 40, 50], encuentra el valor máximo y mínimo.


In [ ]:
# Solución:)
array = np.array([10, 20, 30, 40, 50])
print("El maximo es ", np.max(array), ". El mainimo es ", np.min(array))


El maximo es  50 . El mainimo es  10


### **Ejercicio 5 - Generar números aleatorios:**
  Genera un array de 5 números aleatorios entre 0 y 1.

In [ ]:
# Solución:)
arr2 = np.random.rand(5)
print(arr2)


[0.028022   0.02450101 0.13005921 0.48860384 0.12635976]


### **Ejercicio 6 - Promedio de un array:**
Dado el array [5, 10, 15, 20, 25], calcula su promedio usando NumPy.

In [ ]:
#Solucion:)
arr3= np.array( [5, 10, 15, 20, 25])
print(np.mean(arr3))


15.0


### **Ejercicio 7 - Concatenar dos arrays**
Dados los arrays A = [1, 2, 3] y B = [4, 5, 6], concaténalos en un solo array.

In [ ]:
#Solucion:)
a = np.array([1,2,3])
b = np.array([4,5,6])

c = np.concatenate((a ,b), axis = None)
print(c)

[1 2 3 4 5 6]


### **Ejercicio 8 - Reshape de un Array**
Dado el array [1, 2, 3, 4, 5, 6], cámbialo a una matriz de 2x3.

In [ ]:
#Solución:)
arr6 = np.array([1,2,3,4,5,6])
arrRe = np.reshape(arr6,(2,3))
print(arrRe)

[[1 2 3]
 [4 5 6]]


### **Ejercicio 9 - Producto punto (dot product):**
Dados dos arrays A = [1, 2, 3] y B = [4, 5, 6], calcula su producto punto

In [ ]:
#Solución:)
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.dot(a,b)
print(c)
3*6 + 5*2 + 4

32


32

### **Ejercicio 10 - Reorganizar un array:**
Dado el array [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], conviértelo en una matriz (2, 5).

In [ ]:
#Solución:)
a = np.array([1,2,3,4,5,6,7,8,9,10])
b = np.reshape(a,(2,5))
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


:### **Ejercicio extra - Encontrar el *k*-ésimo elemento más pequeño en un array**
Dado arr = np.array([9, 3, 6, 2, 1, 7]), encuentra el 3er elemento más pequeño sin ordenar el array completo.

**Pista solución 1**: Se puede hacer con un método de Numpy

**Pista solución 2**: El código se hace más complicado, pero se puede resolver con ciclos iterativos.

In [ ]:
#Solucion :o
arr = np.array([9, 3, 6, 2, 1, 7])
k = int(input("ingrese el k-esimo elemento asi deseado "))
if k > len(arr) or k < 1:
  pass
  print("Fuera de rango")
else:
  a = np.partition(arr, k-1)
  print(a[k-1])

ingrese el k-esimo elemento asi deseado 7
Fuera de rango


## **Ejercicios aplicados**

### **Ejercicio: Cálculo de ROI (Retorno de Inversión)**
Dadas las inversiones ([1000, 1500, 2000]) y sus retornos ([1200, 1650, 1800]), calcula el ROI porcentual para cada caso.

*(Fórmula: ROI = (retorno - inversión) / inversión * 100)*

In [ ]:
inversion = np.array([1000,1500,5000])
retorno = np.array([1200,1650,1800])
roi = (retorno - inversion) / inversion * 100
print(roi.astype(int))

[ 20  10 -64]


### **Ejercicio: Normalización de Datos**
Tienes un dataset de precios de productos (en USD): [250, 320, 150, 500, 210]. Normaliza los valores al rango [0, 1] para compararlos en una escala común.

**Formulita de la normalización**: (x - min) / (max - min): Para una escala valores entre 0 y 1.

In [ ]:
arr = np.array([250, 320, 150, 500, 210])
normalizacion = (arr - np.min(arr))/(np.max(arr) - np.min(arr))
print(normalizacion)

[0.28571429 0.48571429 0.         1.         0.17142857]


### **Ejercicio: Filtrado de Datos**
En un array de ventas diarias ([1200, 0, 750, 2400, 0, 1800]), reemplaza los ceros (días sin ventas) por el promedio de los días con ventas.

In [ ]:
ventas = np.array ([1200, 0, 750, 2400, 0, 1800])
ventas_promedio = np.where(ventas == 0 , np.mean(ventas[ventas != 0]), ventas )
print(ventas_promedio)

[1200.  1537.5  750.  2400.  1537.5 1800. ]


### **Ejercicio - Análisis de Presión Arterial**
Tenemos un dataset de mediciones de presión arterial sistólica (mmHg) de 10 pacientes:
[120, 135, 140, 118, 150, 130, 160, 125, 142, 128].

Calculen:
- Media y desviación estándar.
- Identifiquen valores fuera del rango normal (90–140 mmHg).

In [ ]:
presion = np.array( [120, 135, 140, 118, 150, 130, 160, 125, 142, 128])
print(f"Media: {np.mean(presion)}")
print(f"Desviacion estandar: {np.std(presion)}")
print(f"Valores fuera del rango: {presion[(presion < 90 )| (presion > 140)]}")

Media: 134.8
Desviacion estandar: 12.69488085804668
Valores fuera del rango: [150 160 142]


### **Ejercicio - Cálculo del PIB per Cápita**
Dados el PIB (en millones de USD) [500, 320, 700, 450] y la población (en millones) [10, 8, 12, 9] de 4 países, calculen el PIB per cápita y determinen el país con el mayor valor.

In [ ]:
PIB = np.array([500, 320, 700, 450])
poblacion = np.array( [10, 8, 12, 9])
pais = np.array(["A","B", "C","D"])
pibpc = PIB / poblacion
maxpib = np.argmax(pibpc)
print(f"El pais con PIB per capita mas alto es {pais[maxpib]}")
print(f"PIB = {PIB[maxpib]} en millones de USD")
print(f"poblacion = {poblacion[maxpib]} en millones")
print(f"PIB per capita = {pibpc[maxpib]}")


El pais con PIB per capita mas alto es C
PIB = 700 en millones de USD
poblacion = 12 en millones
PIB per capita = 58.333333333333336


### **Ejercicio - Sistema de Drops (Probabilidades)**
En un videojuego RPG, los enemigos al ser vencidos, pueden dropear (soltar):
- 0 = Nada (50%).
- 1 = Poción (30%).
- 2 = Arma (15%).
- 3 = Artefacto (5%).

Simula 100 drops y cuenta cuántos artefactos se obtuvieron.

*Ejemplo de salida*:

```
Artifactos obtenidos: 3
```



In [ ]:
recompensas = np.array([0,1,2,3])
probabilidades = np.array([0.50, 0.30, 0.15, 0.05])
drops = np.random.choice(recompensas, size = 100, p = probabilidades)
print(f"Artefactos obtenidos: {np.sum(drops == 3)}")

Artefactos obtenidos: 5
